### ISSUE TITLE
PHP Fatal error:  Cannot redeclare Pre\Plugin\find() (previously declared in ...

### ISSUE THREAD

**Issue by anibalsanchez** [preprocess/pre-plugin#13]
Hi,

I'm creating a new plugin. Testing the case on **pre-trailing-commas**, I've executed the command `composer dump-autoload --optimize' and produced the error. In some way, the helpers file is being included twice: 

This is the output:

    ...../pre-trailing-commas$ composer update
    Loading composer repositories with package information
    Updating dependencies (including require-dev)
    Package operations: 30 installs, 0 updates, 0 removals
      - Installing pre/plugin (0.11.3): Loading from cache
      - Installing sebastian/version (2.0.1): Loading from cache
      - Installing sebastian/resource-operations (1.0.0): Loading from cache
      - Installing sebastian/recursion-context (3.0.0): Loading from cache
      - Installing sebastian/object-reflector (1.1.1): Loading from cache
      - Installing sebastian/object-enumerator (3.0.3): Loading from cache
      - Installing sebastian/global-state (2.0.0): Loading from cache
      - Installing sebastian/exporter (3.1.0): Loading from cache
      - Installing sebastian/environment (3.1.0): Loading from cache
      - Installing sebastian/diff (2.0.1): Loading from cache
      - Installing sebastian/comparator (2.1.3): Loading from cache
      - Installing doctrine/instantiator (1.1.0): Loading from cache
      - Installing phpunit/php-text-template (1.2.1): Loading from cache
      - Installing phpunit/phpunit-mock-objects (5.0.10): Loading from cache
      - Installing phpunit/php-timer (1.0.9): Loading from cache
      - Installing phpunit/php-file-iterator (1.4.5): Loading from cache
      - Installing theseer/tokenizer (1.1.0): Loading from cache
      - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
      - Installing phpunit/php-token-stream (2.0.2): Loading from cache
      - Installing phpunit/php-code-coverage (5.3.2): Loading from cache
      - Installing symfony/polyfill-ctype (v1.10.0): Loading from cache
      - Installing webmozart/assert (1.4.0): Loading from cache
      - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
      - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
      - Installing phpdocumentor/reflection-docblock (4.3.0): Loading from cache
      - Installing phpspec/prophecy (1.8.0): Loading from cache
      - Installing phar-io/version (1.0.1): Loading from cache
      - Installing phar-io/manifest (1.0.1): Loading from cache
      - Installing myclabs/deep-copy (1.8.1): Loading from cache
      - Installing phpunit/phpunit (6.5.13): Loading from cache
    sebastian/global-state suggests installing ext-uopz (*)
    phpunit/phpunit suggests installing phpunit/php-invoker (^1.1)
    Writing lock file
    Generating autoload files
    ...../pre-trailing-commas$ composer dump-autoload --optimize
    Generating optimized autoload files
    PHP Fatal error:  Cannot redeclare Pre\Plugin\find() (previously declared in /home/...../pre-trailing-commas/vendor/pre/plugin/source/functions.php:5) in /home/...../pre-trailing-commas/vendor/pre/plugin/source/functions.php on line 22

    Fatal error: Cannot redeclare Pre\Plugin\find() (previously declared in /home/...../pre-trailing-commas/vendor/pre/plugin/source/functions.php:5) in /home/...../pre-trailing-commas/vendor/pre/plugin/source/functions.php on line 22

**Comment by assertchris** [comment]
I'll sort out tomorrow. :)

**Comment by assertchris** [comment]
I have released version `0.11.4`, which includes the fix in https://github.com/preprocess/pre-plugin/commit/860c24414758b7fb76f79910d1598357589e327d
