### ISSUE TITLE
Two year old typo + smart tool

### ISSUE THREAD

**Issue by szepeviktor** [preprocess/pre-plugin#23]
@phpstan reveals hard and soft errors! Please consider using it `phpstan analyze source/ -l max`

https://github.com/preprocess/pre-plugin/blob/bd21e7dc70ef47dd948c5abdc1bfbf53dd941e6e/source/Parser.php#L18-L23

**Comment by szepeviktor** [comment]
@assertchris Have you tries @phpstan?

**Comment by assertchris** [comment]
Not for this repo, but I guess I should :)
