### ISSUE TITLE
Use some cache ?

### ISSUE THREAD

**Issue by mathieutu** [preprocess/pre-plugin#6]
Hi!
As I think I've seen, the .pre files are recompiled each time the classes are called by autoloader, even in production. 
I think it should be interesting to make a cache system to avoid recompiling for nothing at each call, or (even better imo) a build system with a command line (webpack/babel like) to compile all the files.

What are your thoughts about that?

Thanks for you amazing work.

**Comment by assertchris** [comment]
If you optimise your autoloader, using `composer install --optimize` or `composer update --optimize` then Pre builds once and then disables itself using a lock file.

**Comment by assertchris** [comment]
There's an exception to this - if you use `Pre\Plugin\process` or the `process` macro; those files are always recompiled. I have yet to think of an elegant way around that.

**Comment by mathieutu** [comment]
Oh! Ok, my bad I'm seeing that now!

It could be interesting to make a piece of documentation about how it works, how add some macros, etc for developers. Don't you think?

**Comment by HallofFamer** [comment]
Okay will do.

**Comment by assertchris** [comment]
https://github.com/preprocess/pre-plugin/pull/11
