### ISSUE TITLE
Update all Pre Macros to use the new sigil($) notation?

### ISSUE THREAD

**Issue by HallofFamer** [preprocess/pre-plugin#9]
Seems that marcioAlmada's Yay library has already updated the master branch to use its new macro syntax, so I think it's time to refactor macros from pre library too? I see you are already doing this for Optional Catch and Trailing Comma too.

I have up-to-date macros for the other pre libraries myself, though I cant get the short-closure one to work properly. Are you interested in receiving these files? I can send them to your email, it will save you some work, while you can make some corrections if I've made a mistake. What do you think?

**Comment by assertchris** [comment]
All done!
